name: Deploiement to my VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Installation de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16
        
    - name: Installation de NPM
      run: npm install

    - name: Build
      run: npm run build

    - name: Envoie vers mon FTP
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        localDir: "./dist/"
        remoteDir: "/home/mmi21g08/public_html/travaux/wra505/dev_front-WRA505D/"
